ECommPortal/Controllers/PlanCouponMappingsController.cs
using ECommPortal.Models;
using ECommPortal.Services;
using ECommPortal.Services.Interface;
using Entities;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ECommPortal.Controllers
{
    public class PlanCouponMappingsController : Controller
    {
        private IPlanCouponMapService apiplancouponmap;
        private IHttpContextAccessor _httpContext;
        private string LoginID;

        public PlanCouponMappingsController(IPlanCouponMapService plan, IHttpContextAccessor httpContext)
        {
            apiplancouponmap = plan;
            _httpContext = httpContext;
            if (_httpContext.HttpContext.Session.Keys.Contains("LoginID"))
                LoginID = _httpContext.HttpContext.Session.GetString("LoginID");
        }
        // GET: PlanCouponMappingsController
        public async Task<ActionResult> Index(CreateCouponPlanMapModel ccpm)
        {

            if (object.Equals(ccpm, null))
            {
                ccpm = new();
            }
            //PlanCouponMapService apiplancouponmap = new PlanCouponMapService();

            //CreateCouponPlanMapModel ccpm = new();
            //plan category
            ccpm.CouponCategoryList = await apiplancouponmap.CouponCategoryapi();
            ccpm.BrandList = await apiplancouponmap.BrandListsApi();
            //int s = 0;
            // // plan api
            //ccpm.PlanList = await apiplancouponmap.Planapi(s);
            if (LoginID != null)
            {
                TempData["UserName"] = LoginID;
                return View(ccpm);
            }
            else
            {
                return RedirectToAction("Index", "Accounts");
            }
        }

        // GET: PlanCouponMappingsController/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: PlanCouponMappingsController/Create
        public async Task<ActionResult> Create(CreateCouponPlanMapModel ccpm)
        {

            // List<CouponPlanMapServiceProperty> cpsp = new();

            //int s = 1;
            // plan api
            ccpm.PlanList = await apiplancouponmap.Planapi(ccpm.couponId, ccpm.ChoosenBranID);
            if (ccpm.couponId > 0)
            {
                ccpm.PlanList = await apiplancouponmap.Planapi(ccpm.couponId,ccpm.ChoosenBranID);
            }
            //string status = "true";

            //for (int i = 0; i < ccpm.ChoosedPlanList.Count; i++)
            //{

            //    if (ccpm.ChoosedPlanList[i].statusvalue)
            //    {
            //        cpsp.Add(new CouponPlanMapServiceProperty()
            //        {
            //            validFrom = ccpm.ValidFrom,
            //            validTo = ccpm.ValidTo,
            //            couponID = (int)ccpm.couponId,
            //            planID = (int)ccpm.ChoosedPlanList[i].ChoosedPlanID

            //        });

            //    }

            //}

            //PlanCouponMapService apiplancoupon = new();


            // var dataobj = await apiplancouponmap.CouponPlanapi(cpsp);


            //string sta = "OK";
            //string msg = "Success";
            //string fmsg = "Failure";

            //if (String.Equals(dataobj.Status, sta) && String.Equals(dataobj.Message, msg))
            //{
            //    ccpm.Responseflag = 0;
            //    ccpm.message = "Plans & Coupon Successfuly Mapped";
            //}
            //else
            //{
            //    if (String.Equals(dataobj.Status, sta) && String.Equals(dataobj.Message, fmsg))
            //    {
            //        ccpm.Responseflag = 1;
            //        ccpm.message = "Plans & Coupon Already Mapped";
            //    }
            //    else
            //    {
            //        ccpm.Responseflag = 1;
            //        ccpm.message = "Discount Course Center Not Successfuly Mapped";
            //    }
            //}

            return View(ccpm);
            //return RedirectToAction("Index", ccpm);

        }

        public async Task<ActionResult> Save(CreateCouponPlanMapModel ccpm)
        {

            //string status = "true";
            List<CouponPlanMapServiceProperty> cpsp = new();
            for (int i = 0; i < ccpm.ChoosedPlanList.Count; i++)
            {

                if (ccpm.ChoosedPlanList[i].statusvalue)
                {
                    cpsp.Add(new CouponPlanMapServiceProperty()
                    {
                        validFrom = ccpm.ValidFrom,
                        validTo = ccpm.ValidTo,
                        couponID = (int)ccpm.couponId,
                        planID = (int)ccpm.ChoosedPlanList[i].ChoosedPlanID

                    });

                }

            }

           // PlanCouponMapService apiplancoupon = new();


            var dataobj = await apiplancouponmap.CouponPlanapi(cpsp);


            string sta = "OK";
            string msg = "Success";
            string fmsg = "Failure";

            if (String.Equals(dataobj.Status, sta) && String.Equals(dataobj.Message, msg))
            {
                ccpm.Responseflag = 0;
                ccpm.message = "Plans & Coupon Successfuly Mapped";
            }
            else
            {
                if (String.Equals(dataobj.Status, sta) && String.Equals(dataobj.Message, fmsg))
                {
                    ccpm.Responseflag = 1;
                    ccpm.message = "Plans & Coupon Already Mapped";
                }
                else
                {
                    ccpm.Responseflag = 1;
                    ccpm.message = "Discount Course Center Not Successfuly Mapped";
                }
            }

            return RedirectToAction("Index", ccpm);
            //return View();
        }

        // POST: PlanCouponMappingsController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
       
        // GET: PlanCouponMappingsController/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: PlanCouponMappingsController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: PlanCouponMappingsController/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: PlanCouponMappingsController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

ECommPortal/Views/PlanCouponMappings/Create.cshtml
@using Entities;
@model ECommPortal.Models.CreateCouponPlanMapModel

@{
    ViewData["Title"] = "Index";
}

<div class="row form-row">


    <div class="col-md-12 ">
        <!-- BEGIN SAMPLE FORM PORTLET-->
        <div class="portlet light form-box">

            <div class="portlet-title">
                <div class="caption color-dark">

                    <span class="caption-subject bold uppercase"> Create Plan Coupon Mapping </span>
                </div>



            </div>

            <div style="display:flex;justify-content:center"><hr class="heading-hr"></div>





            @if (Model.message != null)
            {
                if (Model.Responseflag == 0)
                {
                    <div class="col-md-12" style="background-color:green;padding:2%;width:100%;color:white;">

                        @Model.message

                    </div>
                }

                else
                {
                    <div class="col-md-12" style="background-color:red;padding:2%;width:100%;color:white;">

                        @Model.message

                    </div>

                }


            }
        <div class="portlet-body form global-form">
            @*<form asp-controller="PlanCouponMappings" asp-action="Create">
            <div class="form-body">
                <div class="form-group">
                    <label class="color-dark">Coupon Category</label>
                    <div class="input-group">
                        <select id="coupon-cat" class="coupon-type-class">

                            <option value="" selected>Choose Coupon Category...</option>
                            @foreach (var coup in Model.CouponCategoryList)
                            {
                                <option value=@coup.CouponCategoryID>@coup.CouponCategoryDesc</option>


                            }

                        </select>


                    </div>
                </div>


                <div class="form-group">
                    <label class="color-dark">Coupon Code</label>
                    <div class="input-group">
                        <select id="coupon-items" class="coupon-type-class" asp-for="@Model.couponId">

                            <option value="" selected>Choose Coupon Code...</option>


                        </select>


                    </div>
                </div>
                <div class="form-actions">
                    <button type="submit" class="btn blue">Submit</button>
                </div>

            </div>
        </form>*@

            @if (Model.PlanList != null && Model.couponId > 0)
            {
                <form asp-controller="PlanCouponMappings" asp-action="Save">
                    <div>
                        <input type="hidden" asp-for="@Model.couponId" value="@Model.couponId" />
                        <div class="form-group">
                            <label class="color-dark">Select the plan you want to add</label>
                            <div class="input-group table-form">
                                <input type="text" id="myPlanInput" onkeyup="myPlanFunction()" placeholder="Search for plan names.." title="Type in a name">
                                <div style="width:100%;">
                                    <table id="myPlanTable" class="table table-bordered">
                                        <thead>
                                            <tr>
                                                <th style="width:10%;"></th>
                                                <th style="width:90%;">Plan Name</th>

                                            </tr>
                                        </thead>
                                        <tbody>
                                            @{int i = 0; }
                                            @foreach (var planlist in Model.PlanList)
                                            {



                                                //Model.ChoosedPlanList.Add(new ChoosedPlan());                                            //Model.ChoosedPlanList.Add(new ChoosedPlan());


                                                Model.ChoosedPlanList.Add(new ChoosedPlan());


                                                //Model.ChoosedPlanList[i].ChoosedPlanID = planlist.PlanID;
                                                //Model.ChoosedPlanList[i].ChoosedPlanName = planlist.PlanName;




                                                <tr>

                                                    <td>
                                                        <input type="hidden" value="@planlist.PlanID" asp-for="@Model.ChoosedPlanList[i].ChoosedPlanID" />
                                                        <input type="hidden" value="@planlist.PlanName" asp-for="@Model.ChoosedPlanList[i].ChoosedPlanName" />

                                                        <input type="checkbox" asp-for="@Model.ChoosedPlanList[i].statusvalue" />

                                                        @*@{Model.ChoosedPlanList[i].ChoosedPlanID = planlist.PlanID;}*@
                                                    </td>
                                                    <td> <label asp-for="@Model.ChoosedPlanList[i].statusvalue">@planlist.PlanName</label></td>
                                                </tr>
                                                i++;

                                            }
                                        </tbody>

                                    </table>
                                </div>


                            </div>
                        </div>



                        <div class="form-group flex-form-group" style="margin-bottom:0px !important">
                            <div class="form-group">

                                <label class="color-dark">Valid From</label>
                                <div class="input-group">

                                    <input id="coupon-valid-from" type="date" class="form-control" asp-for="@Model.ValidFrom" value="@DateTime.Now.ToString("yyyy-MM-dd")" min="@DateTime.Now.ToString("yyyy-MM-dd")" required>
                                </div>
                            </div>

                            <div class="form-group">

                                <label class="color-dark">Valid To</label>
                                <div class="input-group">

                                    <input id="coupon-valid-to" type="date" class="form-control" asp-for="@Model.ValidTo" value="@DateTime.Now.ToString("yyyy-MM-dd")" min="@DateTime.Now.ToString("yyyy-MM-dd")" required>
                                </div>
                            </div>
                        </div>




                    </div>
                    <div class="form-actions">
                        <button type="submit" class="btn blue">Submit</button>
                    </div>
                </form>
            }
            else
            {

                <div> No Plans available for Currently Selected Coupon Code </div>
            }
            <br><hr><br>
            <a asp-action="index" asp-controller="PlanCouponMappings"><button type="submit" class="btn blue" style="width:100%">Back</button></a>
        </div>
        </div>
        <!-- END SAMPLE FORM PORTLET-->


    </div>
</div>


<script type="text/javascript">

    function myPlanFunction() {
        var input, filter, table, tr, td, i, txtValue;
        input = document.getElementById("myPlanInput");
        filter = input.value.toUpperCase();
        table = document.getElementById("myPlanTable");
        tr = table.getElementsByTagName("tr");
        for (i = 0; i < tr.length; i++) {
            td = tr[i].getElementsByTagName("td")[1];
            if (td) {
                txtValue = td.textContent || td.innerText;
                if (txtValue.toUpperCase().indexOf(filter) > -1) {
                    tr[i].style.display = "";
                } else {
                    tr[i].style.display = "none";
                }
            }
        }
    }


    function checkfunction(checkboxid, rowno) {

        if (document.getElementById("checkboxid").checked == true) {
            document.getElementById("checkboxid").checked == false;

        }
        else {
              document.getElementById("checkboxid").checked == true;

        }

    }

    jQuery(document).ready(function ($) {

        $('#coupon-valid-from').change(function () {
            document.getElementById("coupon-valid-to").setAttribute("min", document.getElementById("coupon-valid-from").value);
            document.getElementById("coupon-valid-to").value = document.getElementById("coupon-valid-from").value;
        });


        $("#coupon-cat").on('change', function () {
            var e = document.getElementById("coupon-cat");

            $.ajax({
                type: "GET",
                url: "/Ajax/AjaxMethod",
                data: { catid:e.value },
                success: function (response) {
                    console.log(response);
                    var select = document.getElementById('coupon-items');
                    $('#coupon-items')
                        .empty()
                        .append('<option value="" selected>Choose Coupon Code...</option>');

                    for (var i = 0; i < response.length; i++) {

                        var opt = document.createElement('option');
                        opt.value = response[i].couponID;
                        opt.innerHTML = response[i].couponCode;
                        select.appendChild(opt);


                    }
                },
                failure: function (response) {
                    alert(response.responseText);
                },
                error: function (response) {
                    alert(response.responseText);
                }
            });
        });



        /*$("#coupon-items").on('change', function () {
            var e = document.getElementById("coupon-items");

            $.ajax({
                type: "GET",
                url: "/Ajax/AjaxMethodForPlan",
                data: { couponid: e.value },
                success: function (response) {
                    console.log(response);
                    var select = document.getElementById('coupon-items');

                    /*$('#coupon-items')
                        .empty()
                        .append('<option value="" selected>Choose Coupon Code...</option>');

                    for (var i = 0; i < response.length; i++) {

                        var opt = document.createElement('option');
                        opt.value = response[i].couponID;
                        opt.innerHTML = response[i].couponCode;
                        select.appendChild(opt);


                    }*/
              /*  },
                failure: function (response) {
                    alert(response.responseText);
                },
                error: function (response) {
                    alert(response.responseText);
                }
            });
        });*/



    });
</script>

ECommPortal/Views/PlanCouponMappings/Index.cshtml
@using Entities;
@model ECommPortal.Models.CreateCouponPlanMapModel

@{
    ViewData["Title"] = "Index";
}

<div class="row form-row">


    <div class="col-md-12 ">
        <!-- BEGIN SAMPLE FORM PORTLET-->
        <div class="portlet light form-box">

            <div class="portlet-title">
                <div class="caption color-dark">

                    <span class="caption-subject bold uppercase"> Create Plan Coupon Mapping </span>
                </div>



            </div>

            <div style="display:flex;justify-content:center"><hr class="heading-hr"></div>


           


            @if (Model.message != null)
            {
                if (Model.Responseflag == 0)
                {
                    <div class="col-md-12" style="background-color:green;padding:2%;width:100%;color:white;">

                        @Model.message

                    </div>
                }

                else
                {
                    <div class="col-md-12" style="background-color:red;padding:2%;width:100%;color:white;">

                        @Model.message

                    </div>

                }


            }
            <div class="portlet-body form global-form">
                <form asp-controller="PlanCouponMappings" asp-action="Create">
                    <div class="form-body">

                        <div class="form-group">
                            <label class="color-dark">Name of Brand</label>
                            <div id="brand-multiselect" class="input-group">

                                <select id="name-of-brand" class="name-brand-class" asp-for="@Model.ChoosenBranID">


                                    <option value="" selected hidden>Choose Brand Name...</option>
                                    @foreach (var b in Model.BrandList)
                                    {
                                        <option value=@b.BrandID>@b.BrandName</option>

                                    }
                                </select>


                            </div>
                        </div>

                        <div id="cat" style="display:none">
                            <div class="form-group">
                                <label class="color-dark">Coupon Category</label>
                                <div class="input-group">
                                    <select id="coupon-cat" class="coupon-type-class">

                                        <option value="" selected>Choose Coupon Category...</option>
                                        @foreach (var coup in Model.CouponCategoryList)
                                        {
                                            <option value=@coup.CouponCategoryID>@coup.CouponCategoryDesc</option>


                                        }

                                    </select>


                                </div>
                            </div>


                            <div class="form-group">
                                <label class="color-dark">Coupon Code</label>
                                <div class="input-group">
                                    <select id="coupon-items" class="coupon-type-class" asp-for="@Model.couponId">

                                        <option value="" selected>Choose Coupon Code...</option>


                                    </select>


                                </div>
                            </div>
                           </div>
                        <div class="form-actions">
                            <button type="submit" class="btn blue">Fetch</button>
                        </div>

                    </div>
                </form>

            @*    @if (Model.PlanList.Count > -1)*@
                <!--{
                <form asp-controller="PlanCouponMappings" asp-action="Save">
                    <div>
                        <input type="hidden" asp-for="@Model.couponId" value="@Model.couponId" />
                        <div class="form-group">
                            <label class="color-dark">Select the plan you want to add</label>
                            <div class="input-group table-form">
                                <input type="text" id="myPlanInput" onkeyup="myPlanFunction()" placeholder="Search for plan names.." title="Type in a name">
                                <div style="width:100%;">
                                    <table id="myPlanTable" class="table table-bordered">
                                        <thead>
                                            <tr>
                                                <th style="width:10%;"></th>
                                                <th style="width:90%;">Plan Name</th>

                                            </tr>
                                        </thead>
                                        <tbody>
                                            @{int i = 0; }
                                            @foreach (var planlist in Model.PlanList)
                                            {



                                                                                     

                                                Model.ChoosedPlanList.Add(new ChoosedPlan());




                                                <tr>

                                                    <td>
                                                        <input type="hidden" value="@planlist.PlanID" asp-for="@Model.ChoosedPlanList[i].ChoosedPlanID" />
                                                        <input type="hidden" value="@planlist.PlanName" asp-for="@Model.ChoosedPlanList[i].ChoosedPlanName" />

                                                        <input type="checkbox" asp-for="@Model.ChoosedPlanList[i].statusvalue" />

                                                    
                                                    </td>
                                                    <td> <label asp-for="@Model.ChoosedPlanList[i].statusvalue">@planlist.PlanName</label></td>
                                                </tr>
                                                i++;

                                            }
                                        </tbody>

                                    </table>
                                </div>


                            </div>
                        </div>-->



                        @*<div class="form-group flex-form-group" style="margin-bottom:0px !important">
                            <div class="form-group">

                                <label class="color-dark">Valid From</label>
                                <div class="input-group">

                                    <input type="date" class="form-control" asp-for="@Model.ValidFrom" value="@DateTime.Now.ToString("yyyy-MM-dd")" required>
                                </div>
                            </div>

                            <div class="form-group">

                                <label class="color-dark">Valid To</label>
                                <div class="input-group">

                                    <input type="date" class="form-control" asp-for="@Model.ValidTo" value="@DateTime.Now.ToString("yyyy-MM-dd")" required>
                                </div>
                            </div>
                        </div>*@




                    <!--</div>
                    <div class="form-actions">
                        <button type="submit" class="btn blue">Submit</button>
                    </div>
                </form>
                }-->
            </div>
        </div>
        <!-- END SAMPLE FORM PORTLET-->


    </div>
</div>


<script type="text/javascript">

    function myPlanFunction() {
        var input, filter, table, tr, td, i, txtValue;
        input = document.getElementById("myPlanInput");
        filter = input.value.toUpperCase();
        table = document.getElementById("myPlanTable");
        tr = table.getElementsByTagName("tr");
        for (i = 0; i < tr.length; i++) {
            td = tr[i].getElementsByTagName("td")[1];
            if (td) {
                txtValue = td.textContent || td.innerText;
                if (txtValue.toUpperCase().indexOf(filter) > -1) {
                    tr[i].style.display = "";
                } else {
                    tr[i].style.display = "none";
                }
            }
        }
    }


    function checkfunction(checkboxid, rowno) {

        if (document.getElementById("checkboxid").checked == true) {
            document.getElementById("checkboxid").checked == false;
            
        }
        else {
              document.getElementById("checkboxid").checked == true;
            
        }

    }

    jQuery(document).ready(function ($) {

        $("#name-of-brand").on('change', function () {
            if (document.getElementById("name-of-brand").value > 0) {
                document.getElementById("cat").style.display = "block";
            }
            else {
                alert("Please select Correct Brand");
            }
            

        });

        $("#coupon-cat").on('change', function () {
            var e = document.getElementById("coupon-cat");
            var brand = document.getElementById("name-of-brand").value;
            $.ajax({
                type: "GET",
                url: "/Ajax/AjaxMethod",
                data: { catid: e.value, brandid: brand },
                success: function (response) {
                    console.log(response);
                    var select = document.getElementById('coupon-items');
                    $('#coupon-items')
                        .empty()
                        .append('<option value="" selected>Choose Coupon Code...</option>');
                
                    for (var i = 0; i < response.length; i++) {

                        var opt = document.createElement('option');
                        opt.value = response[i].couponID;
                        opt.innerHTML = response[i].couponCode;
                        select.appendChild(opt);


                    }
                },
                failure: function (response) {
                    alert(response.responseText);
                },
                error: function (response) {
                    alert(response.responseText);
                }
            });
        });



        /*$("#coupon-items").on('change', function () {
            var e = document.getElementById("coupon-items");

            $.ajax({
                type: "GET",
                url: "/Ajax/AjaxMethodForPlan",
                data: { couponid: e.value },
                success: function (response) {
                    console.log(response);
                    var select = document.getElementById('coupon-items');
                    
                    /*$('#coupon-items')
                        .empty()
                        .append('<option value="" selected>Choose Coupon Code...</option>');

                    for (var i = 0; i < response.length; i++) {

                        var opt = document.createElement('option');
                        opt.value = response[i].couponID;
                        opt.innerHTML = response[i].couponCode;
                        select.appendChild(opt);


                    }*/
              /*  },
                failure: function (response) {
                    alert(response.responseText);
                },
                error: function (response) {
                    alert(response.responseText);
                }
            });
        });*/



    });
</script>