ECommPortal/Models/PlanListingViewModel.cs
using ECommPortal.Models.ValueObjects;
using Entities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ECommPortal.Models
{
    public class PlanListingViewModel : ResponseModel
    {
        public string choosenBrandListString { get; set; }
        public List<Brand> BrandLists { get; set; } = new();
        public List<int> ChoosenBrandLists { get; set; } = new();
        public List<Plan> PlanLists { get; set; } = new();
        public List<Plan> ChoosedUpdatedPlanLists { get; set; } = new();

    }
}

ECommPortal/Controllers/PlanListingController.cs
using ECommPortal.Models;
using ECommPortal.Services;
using ECommPortal.Services.Interface;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ECommPortal.Controllers
{
    public class PlanListingController : Controller
    {

        private IPlanListingService apiplanlist;

        public PlanListingController(IPlanListingService apiplanlistobj)
        {
            apiplanlist = apiplanlistobj;
        }
        // GET: PlanListingController
        public async Task<ActionResult> Index()
        {
            PlanListingViewModel plvm = null;
            //AllDiscountServices apidiscount = new AllDiscountServices();
            if (TempData.ContainsKey("planlistObj") && TempData["planlistObj"] != null)
            {
                plvm = JsonConvert.DeserializeObject<PlanListingViewModel>(TempData["planlistObj"].ToString());
            }
            //Console.WriteLine(x);
            if (object.Equals(plvm, null))
            {
                plvm = new();
            }


            plvm.BrandLists = await apiplanlist.BrandListsApi();

            if (plvm.ChoosenBrandLists.Count > 0 && plvm.choosenBrandListString != null)
            {
                plvm.PlanLists = await apiplanlist.GetPlanListsApi(plvm.choosenBrandListString);
            }

            return View(plvm);
        }

        // GET: PlanListingController/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: PlanListingController/Create
        public ActionResult Create(PlanListingViewModel plvm)
        {
            if (plvm.ChoosenBrandLists == null)
            {
                plvm.ChoosenBrandLists = new();
            }
            else
            {
                for (int i = 0; i < plvm.ChoosenBrandLists.Count; i++)
                {
                    if (i == 0)
                    {

                        plvm.choosenBrandListString = "" + plvm.ChoosenBrandLists[i];
                    }
                    else
                    {
                        plvm.choosenBrandListString+= ","+plvm.ChoosenBrandLists[i];
                    }
                }
            }

            TempData["planlistObj"] = JsonConvert.SerializeObject(plvm);
            return RedirectToAction("Index");
        }


        public ActionResult Save(PlanListingViewModel plvm)
        {
            return RedirectToAction("Index");
        }


        // GET: PlanListingController/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: PlanListingController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: PlanListingController/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: PlanListingController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

ECommPortal/Views/PlanListing/Index.cshtml
@using Entities;
@model ECommPortal.Models.PlanListingViewModel

@{
    ViewData["Title"] = "Index";
}

<div class="row form-row">


    <div class="col-md-12 ">
        <!-- BEGIN SAMPLE FORM PORTLET-->
        <div class="portlet light form-box">

            <div class="portlet-title">
                <div class="caption color-dark">

                    <span class="caption-subject bold uppercase"> Publish / Deactive Plans </span>
                </div>



            </div>

            <div style="display:flex;justify-content:center"><hr class="heading-hr"></div>





            @if (Model.message != null)
            {
                if (Model.Responseflag == 0)
                {
                    <div class="col-md-12" style="background-color:green;padding:2%;width:100%;color:white;">

                        @Model.message

                    </div>
                }

                else
                {
                    <div class="col-md-12" style="background-color:red;padding:2%;width:100%;color:white;">

                        @Model.message

                    </div>

                }


            }
            <div class="portlet-body form global-form">
                <form asp-controller="PlanListing" asp-action="Create">
                    <div class="form-body">

                        <div class="form-group">
                        <label class="color-dark">Name of Brand</label>
                        <div id="brand-multiselect" class="input-group">

                            <select id="name-of-brand" class="name-brand-class form-table-select multiple-selection" asp-for="@Model.ChoosenBrandLists" multiple data-live-search="true">


                                @foreach (var b in Model.BrandLists)
                                {
                                    <option value=@b.BrandID>@b.BrandName</option>

                                }
                            </select>


                        </div>
                        </div>

                        <div class="form-actions">
                            <button type="submit" class="btn blue">Submit</button>
                        </div>

                    </div>
                </form>

                @if (Model.ChoosenBrandLists.Count > 0)
                {
                    if (Model.PlanLists != null)
                    {
                        int count = Model.PlanLists.Count;


                        <form asp-controller="PlanListing" asp-action="Save">
                            <div>
                                <input type="hidden" asp-for="@Model.choosenBrandListString" value="@Model.choosenBrandListString" />
                                <div class="form-group">
                                    <label class="color-dark">Select the Plan you want to Publish/Deactive</label>
                                    <br>
                                    <div class="input-group table-form" style="margin-top:10px;">
                                        <div class="functional-div" style="display:flex;">
                                            <div id="publish-button" class="action-button" style="color:white;background:green;border:1px solid green;" onClick="myPublishFunction(@count)"><span><i class="fa fa-check" aria-hidden="true"></i></span> Publish</div>
                                            <div id="deactive-button" class="action-button" style="color:white;background:red;border:1px solid red;" onClick="myDeactiveFunction(@count)"><span><i class="fa fa-times" aria-hidden="true"></i></span> Deactivation</div>
                                            <input type="text" id="myPlanInput" onkeyup="myPlanFunction()" placeholder="Search for Plan.." title="Type in a name" style="padding: 4px 20px 4px 40px !important;">
                                        </div>
                                        <br>
                                        <div style="width:100%;margin-top:10px;">
                                            <table id="myPlanTable" class="table table-bordered">
                                                <thead>
                                                    <tr>
                                                        <th style="width:5%;"></th>
                                                        <th style="width:70%;">Plan Name</th>
                                                        <th style="width:25%;">Action</th>

                                                    </tr>
                                                </thead>
                                                <tbody>
                                                    @{int i = 0; }
                                                    @foreach (var planlist in Model.PlanLists)
                                                    {

                                                        string rowid = "rowid" + i.ToString();
                                                        string selectplan = "selectplan" + i.ToString();
                                                        string updateddeactive = "updateddeactive" + i.ToString();
                                                        string updatedpublish = "updatedpublish" + i.ToString();
                                                        string planpublishedvalueid = "plantpublishedvalue" + i.ToString();

                                                        Model.ChoosedUpdatedPlanLists.Add(new Plan());



                                                        <tr id="@rowid">

                                                            <td>
                                                                <input type="hidden" value="@planlist.PlanID" asp-for="@Model.ChoosedUpdatedPlanLists[i].PlanID" />
                                                                <input type="hidden" value="@planlist.PlanName" asp-for="@Model.ChoosedUpdatedPlanLists[i].PlanName" />

                                                                <input id="@selectplan" type="checkbox" />

                                                                @*@{Model.ChoosedPlanList[i].ChoosedPlanID = planlist.PlanID;}*@
                                                            </td>
                                                            <td> <label asp-for="@Model.ChoosedUpdatedPlanLists[i].PlanID">@planlist.PlanName</label></td>
                                                            <td>
                                                                <input id="@planpublishedvalueid" class="published-checkbox" type="checkbox" value="@planlist.IsPublished" asp-for="@Model.ChoosedUpdatedPlanLists[i].IsPublished">
                                                                @if (@planlist.IsPublished)
                                                                {
                                                                    <div id="@updateddeactive" style="display: block; color: white; background: red; border: 1px solid red; padding: 7px 14px !important; border-radius: 20px !important;width:fit-content;"><span><i class="fa fa-times" aria-hidden="true"></i></span> Deactivation</div>
                                                                    <div type="text" id="@updatedpublish" style="display: none; color: white; background: green; border: 1px solid green; padding: 7px 14px !important; border-radius: 20px !important; width: fit-content; "><span><i class="fa fa-check" aria-hidden="true"></i></span> Publish</div>
                                                                }
                                                                else
                                                                {
                                                                    <div id="@updateddeactive" style="display: none; color: white; background: red; border: 1px solid red; padding: 7px 14px !important; border-radius: 20px !important; width: fit-content; "><span><i class="fa fa-times" aria-hidden="true"></i></span> Deactivation</div>
                                                                    <div type="text" id="@updatedpublish" style="display: block; color: white; background: green; border: 1px solid green; padding: 7px 14px !important; border-radius: 20px !important; width: fit-content; "><span><i class="fa fa-check" aria-hidden="true"></i></span> Publish</div>
                                                                }

                                                            </td>
                                                        </tr>
                                                        i++;

                                                    }
                                                </tbody>

                                            </table>
                                        </div>


                                    </div>
                                </div>


                            </div>
                            <div class="form-actions">
                                <button type="submit" class="btn blue">Submit</button>
                            </div>
                        </form>
                    }

                    else
                    {

                        <div style="color:red;">**** Please select Correct Brand</div>

                    }
                }

            </div>
        </div>
        <!-- END SAMPLE FORM PORTLET-->


    </div>
</div>


<script type="text/javascript">

    function myPublishFunction(plancount) {

        for (let i = 0; i < productcount; i++) {
            var selectplan = "selectplan" + i.toString();
            var updateddeactive = "updateddeactive" + i.toString();
            var updatedpublish = "updatedpublish" + i.toString();
            var planpublishedvalueid = "planpublishedvalue" + i.toString();

            if (document.getElementById(selectplan).checked == true) {

                document.getElementById(planpublishedvalueid).checked = true;
                document.getElementById(planpublishedvalueid).value = true;
             document.getElementById(updateddeactive).style.display = "block";
             document.getElementById(updatedpublish).style.display = "none";
           }



        }

    }




    function myDeactiveFunction(plancount) {

        for (let i = 0; i < productcount; i++) {
            var selectplan = "selectplan" + i.toString();
            var updateddeactive = "updateddeactive" + i.toString();
            var updatedpublish = "updatedpublish" + i.toString();
            var planpublishedvalueid = "planpublishedvalue" + i.toString();

            if (document.getElementById(selectplan).checked == true) {

                document.getElementById(planpublishedvalueid).checked = false;
                document.getElementById(updateddeactive).style.display = "none";
                document.getElementById(updatedpublish).style.display = "block";
            }



        }

    }



    function myProductFunction() {
        var input, filter, table, tr, td, i, txtValue;
        input = document.getElementById("myPlanInput");
        filter = input.value.toUpperCase();
        table = document.getElementById("myPlanTable");
        tr = table.getElementsByTagName("tr");
        for (i = 0; i < tr.length; i++) {
            td = tr[i].getElementsByTagName("td")[1];
            if (td) {
                txtValue = td.textContent || td.innerText;
                if (txtValue.toUpperCase().indexOf(filter) > -1) {
                    tr[i].style.display = "";
                } else {
                    tr[i].style.display = "none";
                }
            }
        }
    }
    $('.multiple-selection').selectpicker();
    $(".filter-option-inner-inner").html("Choose Brand Name...");
   
</script>